Repository wiremock/wiremock-testcontainers-java, pull requests merged in 2023-04, with the labels that each got.

#3 Automate releases to GitHub Packages
  .github/workflows/release.yml
  pom.xml
Labels: chore

#4 Change the tag name format to use just the version number as in wiremock/wiremock
  pom.xml
Labels: chore

#5 Add JReleaser configuration
  jreleaser.yml
Labels: chore

#6 Fix naming in the docs. Testcontainers, not TestContainers
  README.md
  jreleaser.yml
  pom.xml
Labels: bug, documentation

#7 Fix test
  pom.xml
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionTest.java
  src/test/resources/logback-test.xml
Labels: chore

#10 Feature/Re-organize Dependencies and enable Juni4 & Junit5 execution togeter
  pom.xml
Labels: enhancement, chore

#11 Improve formatting of the unit test
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerTest.java
Labels: chore

#17 Ignore .DS_Store files
  .gitignore
Labels: chore

#14 Add @oleg-nenashev as a code owner and default reviewer
  .github/CODEOWNERS
Labels: chore

#15 Enable Dependabot in the repository
  .github/workflows/dependabot.yml
Labels: chore

#13 Update the release flow to take the version as a parameter, and pass it to JReleaser
  .github/workflows/release.yml
  jreleaser.yml
Labels: chore

#23 Add Release Drafter to the repository
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#16 Add JUnit5 test coverage and documentation
  README.md
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerJUnit5Test.java
Labels: documentation, chore

#25 Add waiting strategy to make sure that wiremock server up and running
  src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
Labels: enhancement

#24 Fix SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder"
  pom.xml
Labels: bug

#29 Disable JReleaser in the release pipeline
  .github/workflows/release.yml
Labels: chore

#30 README: Use the HTTPs URL for the Slack channel
  README.md
Labels: chore
