Repository wiremock/wiremock-testcontainers-java, pull requests merged in 2023-05, with the labels that each got.

#35 Allow to override waiting strategy and waiting time
  src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
Labels: bug

#39 Reduce Code duplication in tests and make tests easier to read
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionTest.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsCombinationTest.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerJUnit5Test.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerTest.java
  src/test/java/org/wiremock/integrations/testcontainers/testsupport/http/TestHttpClient.java
Labels: chore

#42 Disable WireMock banner in the CLI output by default
  src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerJUnit5Test.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerUnitTest.java
Labels: enhancement

#40 Webhook test and Testcontainers networking
  pom.xml
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsWebhookTest.java
  src/test/java/org/wiremock/integrations/testcontainers/testsupport/http/TestHttpServer.java
  src/test/resources/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsWebhookTest/webhook-callback-template.json
Labels: chore

#45 Use global configuration of the Release Drafter
  .github/release-drafter.yml
Labels: chore

#46 Java 1.8 compatibility
  pom.xml
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionTest.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsCombinationTest.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsWebhookTest.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerJUnit5Test.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerTest.java
  src/test/java/org/wiremock/integrations/testcontainers/testsupport/http/HttpResponse.java
  src/test/java/org/wiremock/integrations/testcontainers/testsupport/http/TestHttpClient.java
  src/test/java/org/wiremock/integrations/testcontainers/testsupport/http/TestHttpServer.java
Labels: enhancement

#48 Run CI against all supported Java versions: 8, 11, 17
  .github/workflows/ci.yml
Labels: chore
