Repository wiremock/wiremock-testcontainers-java, pull requests merged in 2023-10, with the labels that each got.

#76 Add /health endpoint in waiting strategy
  src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerWithWireMockVersionThreeTest.java
Labels: enhancement

#77 Add Maven Central release configuration
  .github/workflows/release.yml
  pom.xml
Labels: chore

#84 Use the legacy OSSRH server
  pom.xml
Labels: chore

#85 Add Maven metadata for the project and developers
  pom.xml
Labels: documentation

#86 Release the module to Maven Central
  README.md
Labels: enhancement
