Repository wiremock/wiremock-testcontainers-java, pull requests merged in 2025-03, with the labels that each got.

#171 fix: Use addExposedPort instead of setExposedPort which overrides user configuration
  src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerJunit4Test.java
  src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerTest.java
Labels: bug

#178 Add FUNDING as I am finally able to commit more maintenance time
  .github/FUNDING.yml
Labels: chore

#179 Extend the contributor guide, list steps towards 1.0
  CONTRIBUTING.md
  LICENSE.txt
  README.md
  jreleaser.yml
Labels: documentation
